### PR TITLE
Material Icons Update

### LINKED ISSUE #152: Material icons CSS does not contain material-icons style anymore
**Describe the bug**
In 3.1.5 version of `fontsource-material-icons`, the index.css files contains in addition to the font face source:
```css
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -moz-font-feature-settings: 'liga';
  -moz-osx-font-smoothing: grayscale;
}
```

This style is not present anymore in `@fontsource/material-icons` for version 4.2.0.
I had a look in https://github.com/fontsource/fontsource/blob/master/CHANGELOG.md and I do not find anything regarding this breaking change.

Is this change intentional?

### PR DESCRIPTION
**Pull request by ayuhito**
Closes #152, #158 and #172.

Adds Material Icons Outlined, Sharp and Two Tone.
Updates Material Icons to v4.

### CODE REVIEW

**Comment by Maximaximum** [comment]
Hey @DecliningLotus, thanks for the update! Would you mind letting us know when the updated `@fontsource/material-icons` package version (containing these changes) will be released?

**Comment by ayuhito** [comment]
@Maximaximum, it's out now. Was having some issues with Lerna but we're all good now!

**Comment by Maximaximum** [comment]
@DecliningLotus thanks a lot! It seems to be working now, but some icons are still missing. Made a comment here: https://github.com/fontsource/fontsource/issues/172

**Comment by ayuhito** [comment]
@Maximaximum, I'll check it out soon but I'm a little unsure considering these are the latest files from the official Google repo.

**Pull request merged**
