### PR TITLE
Add Open Sauce fonts (Open Sauce Sans, Open Sauce One, Open Sauce Two)

### LINKED ISSUE #569: Font Request: Open Sauce Fonts (Open Sauce Sans, Open Sauce One, Open Sauce Two)
**Font Name**
Open Sauce Fonts (Open Sauce Sans, Open Sauce One, Open Sauce Two)

**Link to font source**
https://github.com/marcologous/Open-Sauce-Fonts

**Link to font license**

- License for Open Sauce One: https://github.com/marcologous/Open-Sauce-Fonts/blob/master/Open%20Sauce%20One%20OFL.txt
- License for Open Sauce Sans: https://github.com/marcologous/Open-Sauce-Fonts/blob/master/Open%20Sauce%20Sans%20OFL.txt
- License for Open Sauce Two: https://github.com/marcologous/Open-Sauce-Fonts/blob/master/Open%20Sauce%20Two%20OFL.txt

**Additional context**
These fonts are widely used in a lot of design work, especially now that Canva is using OS1 in their systems.

The only catch is that the only formats I could find for all of this are in TTF.

### PR DESCRIPTION
**Pull request by samhwang**
This PR Adds the Open Sauce Sans, Open Sauce One and Open Sauce Two fonts. Resolves #569 

These files are copied as TTF from https://github.com/marcologous/Open-Sauce-Fonts and converted to WOFF and WOFF2 via https://onlinefontconverter.com/

The licenses for these fonts are also in that GitHub repo.

### CODE REVIEW

**Review by ayuhito — CHANGES_REQUESTED** [review]
You should move the font folders into `fonts/other` instead of the current `fonts/generic`. Looks good otherwise!

**Comment by samhwang** [comment]
Hey @ayuhito thanks for the fast review!

> Once ready, copy over the new package folder found in `./scripts/generic` over to the main packages directory, `./fonts/generic`. Make sure to delete the generated files in `./scripts/generic`. Create a pull request, it'll be reviewed and added to the repository!

I was putting the fonts in `fonts/generic` because of this instruction in the `scripts/generic/README.md`, but I'll update that to `fonts/other`.

**Comment by ayuhito** [comment]
> I was putting the fonts in `fonts/generic` because of this instruction in the `scripts/generic/README.md`, but I'll update that to `fonts/other`.

Yeah, this is really outdated. I'm planning on reworking the entire generic packager so adding new fonts would be much much easier in the future, but that's still a while away.

**Comment by samhwang** [comment]
Updated!

**Review by ayuhito — APPROVED** [review]

**Comment by ayuhito** [comment]
Awesome. It should take around 15 mins to publish onto NPM once merged. Thanks!

**Pull request merged**
